apiVersion: v1
kind: Service
metadata:
    name: web
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: web
---
apiVersion: v1
kind: Service
metadata:
    name: leaderboard2
spec:
    type: LoadBalancer
    ports:
    - port: 80
    selector:
        app: leaderboard
